version: '3.8'
services:
  authdb:
    image: postgres:12
    container_name: 'authdb'
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - '5438:5432'
    volumes:
      - authdb:/var/lib/postgresql/data
      - ./docker/authdb/initdb:/docker-entrypoint-initdb.d
    networks:
      - postgres
    restart: unless-stopped
volumes:
  authdb:
    driver: local
networks:
  postgres:
