CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(128) NOT NULL PRIMARY KEY,
  email VARCHAR(128) NOT NULL UNIQUE,
  encrypted_password VARCHAR(255) NOT NULL,
  aud VARCHAR(255) NOT NULL,
  role VARCHAR(40) NOT NULL,
  raw_user_meta_data JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  invited_at TIMESTAMP WITH TIME ZONE,
  confirmed_at TIMESTAMP WITH TIME ZONE,
  confirmation_token VARCHAR(128),
  confirmation_sent_at TIMESTAMP WITH TIME ZONE,
  last_sign_in_at TIMESTAMP WITH TIME ZONE,
  recover_token VARCHAR(128),
  recover_sent_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
  id VARCHAR(128) NOT NULL PRIMARY KEY,
  token VARCHAR(128) NOT NULL,
  user_id VARCHAR(128) NOT NULL,
  revoked BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_refresh_tokens
    FOREIGN KEY (user_id)
      REFERENCES users(id)
      ON DELETE CASCADE
);
